-- 코드를 작성해주세요
SELECT T.ID
FROM ECOLI_DATA AS T INNER JOIN (SELECT F.ID AS first_id, S.ID AS second_id
FROM ECOLI_DATA F INNER JOIN ECOLI_DATA S ON F.ID=S.PARENT_ID
WHERE F.PARENT_ID IS NULL) AS CA ON T.PARENT_ID = CA.second_id
ORDER BY T.ID;