-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE,ROUND(((C.DAILY_FEE*(100-P.DISCOUNT_RATE)/100)*30),0) AS FEE

FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE=P.CAR_TYPE
LEFT JOIN
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE  (END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')) AS DAYS ON C.CAR_ID=DAYS.CAR_ID

WHERE DAYS.CAR_ID IS NULL AND (P.DURATION_TYPE = '30일 이상') AND (C.CAR_TYPE='세단' OR C.CAR_TYPE='SUV')
AND ROUND(((C.DAILY_FEE*(100-P.DISCOUNT_RATE)/100)*30),0)>=500000
AND ROUND(((C.DAILY_FEE*(100-P.DISCOUNT_RATE)/100)*30),0)<2000000
GROUP BY C.CAR_ID
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;
