-- 코드를 입력하세요
SELECT K.CAR_ID, K.CAR_TYPE,ROUND(K.FEE) AS FEE

FROM 
(SELECT C.CAR_ID,C.CAR_TYPE,C.DAILY_FEE,P.DISCOUNT_RATE,
    30*(100-TRIM(LEADING '%' FROM P.DISCOUNT_RATE))/100*C.DAILY_FEE AS FEE
 
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE=P.CAR_TYPE
WHERE C.CAR_ID NOT IN (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE>='2022-11-01' AND START_DATE <= '2022-11-30')
AND C.CAR_TYPE IN ('SUV','세단') AND P.DURATION_TYPE='30일 이상') AS K
WHERE FEE>=500000 AND FEE<2000000
ORDER BY K.FEE DESC ,K.CAR_TYPE, K.CAR_ID DESC;
