-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) AS YEAR,
MONTH(S.SALES_DATE) AS MONTH,
COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT S.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'),1) AS PUCHASED_RATIO

FROM USER_INFO I INNER JOIN ONLINE_SALE S ON I.USER_ID=S.USER_ID
WHERE I.JOINED LIKE '2021%'
GROUP BY YEAR,MONTH
ORDER BY YEAR,MONTH;