-- 코드를 작성해주세요
#그룹바이에서 month만 기준으로 4개의 쿼터로 나눔, 그리고 id를 카운트
SELECT  CASE
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12 THEN '4Q'
    END AS QUARTER,
COUNT(ID) AS ECOLI_COUNT
FROM ECOLI_DATA

GROUP BY
    CASE
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3
        THEN '1Q'    
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6
        THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9
        THEN '3Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12
        THEN '4Q'
    END
ORDER BY QUARTER;