-- 코드를 입력하세요
# +1 해줘야함

SELECT T.HISTORY_ID, 
        CASE 
            WHEN T.cnt>=90 THEN T.DAILY_FEE*(100-P.DISCOUNT_RATE)/100*T.cnt
            WHEN T.cnt>=30 THEN T.DAILY_FEE*(100-P.DISCOUNT_RATE)/100*T.cnt
            WHEN T.cnt>=7 THEN T.DAILY_FEE*(100-P.DISCOUNT_RATE)/100*T.cnt
        ELSE T.DAILY_FEE*cnt
        END AS FEE
    
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P right outer join
(SELECT C.CAR_TYPE,H.HISTORY_ID, C.DAILY_FEE, DATEDIFF(H.END_DATE,H.START_DATE) + 1 as cnt,
        CASE 
            WHEN DATEDIFF(H.END_DATE,H.START_DATE) + 1 >= 90 THEN '90일 이상'
            when DATEDIFF(H.END_DATE,H.START_DATE) + 1 >= 30 THEN '30일 이상'
            when DATEDIFF(H.END_DATE,H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE '해당없음'
        END AS DAYS
    from CAR_RENTAL_COMPANY_CAR C join CAR_RENTAL_COMPANY_RENTAL_HISTORY H on C.CAR_ID=H.CAR_ID
    where C.CAR_TYPE = '트럭') AS T 
ON P.DURATION_TYPE=T.DAYS
and P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, T.HISTORY_ID DESC;