-- 코드를 입력하세요

with recursive T AS (
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR+1 
    FROM T
    WHERE HOUR<23)



SELECT T.HOUR,IFNULL(K.COUNT,0) AS COUNT
FROM T LEFT JOIN 
    (SELECT DATE_FORMAT(DATETIME,'%H') AS HOUR , COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR) AS K ON T.HOUR=K.HOUR
ORDER BY T.HOUR;