-- 코드를 입력하세요
SELECT U.USER_ID,U.NICKNAME,SUM(D.PRICE) AS TOTAL_SALES

FROM USED_GOODS_USER U INNER JOIN
(SELECT WRITER_ID,PRICE
FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE') AS D ON U.USER_ID=D.WRITER_ID	
GROUP BY U.USER_ID
HAVING TOTAL_SALES>=700000

ORDER BY TOTAL_SALES;