-- 코드를 입력하세요
#진료과코드로 그룹
#카운트 환자번호 PT_NO

SELECT MCDP_CD AS '진료과코드',COUNT(PT_NO) AS '5월예약건수'
FROM APPOINTMENT
WHERE (YEAR(APNT_YMD)=2022) AND (MONTH(APNT_YMD)=5)
GROUP BY MCDP_CD
ORDER BY COUNT(PT_NO),MCDP_CD

