-- 코드를 입력하세요
-- 10월은 31일까지 있다.
SELECT MONTH(START_DATE) AS MONTH,CAR_ID,COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

WHERE '2022-08-01'<=START_DATE AND START_DATE<='2022-10-31' AND   
    CAR_ID IN
        (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE '2022-08-01'<=START_DATE AND START_DATE<='2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(HISTORY_ID)>=5)

GROUP BY MONTH,CAR_ID
#HAVING RECORDS>=1
ORDER BY MONTH,CAR_ID DESC;