-- 코드를 작성해주세요
#파이썬 256 와 &해서 256이거나
#C# 1024 와 & 해서 1024면

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME ='Python') 
OR 
SKILL_CODE&(SELECT CODE FROM SKILLCODES WHERE NAME ='C#')
ORDER BY ID;